### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by josego85** [chimo/gs-share#5]
When I perform any action as selecting a date in jquery element, I get the following error Uncaught TypeError: Cannot read property 'classList' of null.

As podira fix this?
thanks, jose

**Comment by chimo** [comment]
Hi!

This should be fixed in the [new release](https://github.com/chimo/gs-share/releases/tag/v0.1.1).

**Comment by josego85** [comment]
Now works. thank you
